version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    links:
      - goapp
    ports:
      - "8080:80"

  goapp:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        secret: SECRET
        dbconnect: mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - ./mongodb:/data/db